combos = [
    {"prefix": "ab", "stem": "kommen", "meaning": "move away", "hint": "(without noticing)"},
    {"prefix": "ab", "stem": "kommen", "meaning": "deviate", "hint": ""},
    {"prefix": "ab", "stem": "nehmen", "meaning": "decrease", "hint": ""},
    {"prefix": "ab", "stem": "nehmen", "meaning": "remove", "hint": ""},
    {"prefix": "ab", "stem": "setzen", "meaning": "take off", "hint": "(glasses)"},
    {"prefix": "ab", "stem": "setzen", "meaning": "set down", "hint": "(a suitcase, out of a car)"},
    {"prefix": "ab", "stem": "stellen", "meaning": "put down", "hint": ""},
    {"prefix": "ab", "stem": "stellen", "meaning": "put away", "hint": "(in an attic)"},
    {"prefix": "ab", "stem": "stellen", "meaning": "park", "hint": ""},
    {"prefix": "an", "stem": "kommen", "meaning": "arrive", "hint": ""},
    {"prefix": "an", "stem": "nehmen", "meaning": "assume", "hint": ""},
    {"prefix": "an", "stem": "nehmen", "meaning": "accept", "hint": ""},
    {"prefix": "an", "stem": "nehmen", "meaning": "adopt", "hint": ""},
    {"prefix": "an", "stem": "nehmen", "meaning": "take on", "hint": ""},
    {"prefix": "an", "stem": "setzen", "meaning": "position", "hint": ""},
    {"prefix": "an", "stem": "setzen", "meaning": "start", "hint": ""},
    {"prefix": "an", "stem": "stellen", "meaning": "queue", "hint": ""},
    {"prefix": "an", "stem": "stellen", "meaning": "lean against", "hint": ""},
    {"prefix": "auf", "stem": "kommen", "meaning": "come up", "hint": ""},
    {"prefix": "auf", "stem": "nehmen", "meaning": "record", "hint": ""},
    {"prefix": "auf", "stem": "nehmen", "meaning": "pick up", "hint": ""},
    {"prefix": "auf", "stem": "nehmen", "meaning": "take in", "hint": "(news, info, refugees)"},
    {"prefix": "auf", "stem": "nehmen", "meaning": "include", "hint": ""},
    {"prefix": "auf", "stem": "setzen", "meaning": "draw up", "hint": "(a contract)"},
    {"prefix": "auf", "stem": "setzen", "meaning": "put on", "hint": "(a hat)"},
    {"prefix": "auf", "stem": "stellen", "meaning": "set up", "hint": "(establish, erect)"},
    {"prefix": "auf", "stem": "stellen", "meaning": "position", "hint": ""},
    {"prefix": "aus", "stem": "kommen", "meaning": "get along", "hint": ""},
    {"prefix": "aus", "stem": "nehmen", "meaning": "exempt", "hint": ""},
    {"prefix": "aus", "stem": "nehmen", "meaning": "gut", "hint": ""},
    {"prefix": "aus", "stem": "setzen", "meaning": "suspend", "hint": ""},
    {"prefix": "aus", "stem": "setzen", "meaning": "expose", "hint": ""},
    {"prefix": "aus", "stem": "setzen", "meaning": "abandon", "hint": "(a dog)"},
    {"prefix": "aus", "stem": "stellen", "meaning": "issue", "hint": ""},
    {"prefix": "aus", "stem": "stellen", "meaning": "exhibit", "hint": ""},
    {"prefix": "be", "stem": "kommen", "meaning": "receive", "hint": ""},
    {"prefix": "be", "stem": "kommen", "meaning": "catch", "hint": "(a train)"},
    {"prefix": "be", "stem": "nehmen", "meaning": "behave", "hint": ""},
    {"prefix": "be", "stem": "setzen", "meaning": "fill", "hint": "(a position)"},
    {"prefix": "be", "stem": "setzen", "meaning": "occupy", "hint": ""},
    {"prefix": "be", "stem": "stellen", "meaning": "order", "hint": ""},
    {"prefix": "ein", "stem": "nehmen", "meaning": "take", "hint": "(tea, tablet)"},
    {"prefix": "ein", "stem": "nehmen", "meaning": "take", "hint": "(while fighting/occupying)"},
    {"prefix": "ein", "stem": "nehmen", "meaning": "take in", "hint": "(money, patients)"},
    {"prefix": "ein", "stem": "setzen", "meaning": "insert", "hint": ""},
    {"prefix": "ein", "stem": "setzen", "meaning": "use", "hint": "(apply)"},
    {"prefix": "ein", "stem": "stellen", "meaning": "hire", "hint": ""},
    {"prefix": "ein", "stem": "stellen", "meaning": "cease", "hint": ""},
    {"prefix": "ein", "stem": "stellen", "meaning": "set", "hint": "(as in settings)"},
    {"prefix": "vor", "stem": "kommen", "meaning": "appear", "hint": ""},
    {"prefix": "vor", "stem": "kommen", "meaning": "occur", "hint": ""},
    {"prefix": "vor", "stem": "nehmen", "meaning": "carry out", "hint": ""},
    {"prefix": "vor", "stem": "nehmen", "meaning": "bring forward", "hint": ""},
    {"prefix": "vor", "stem": "setzen", "meaning": "prefix", "hint": ""},
    {"prefix": "vor", "stem": "setzen", "meaning": "put in front of", "hint": "(drinks in front of a guest)"},
    {"prefix": "vor", "stem": "stellen", "meaning": "imagine", "hint": ""},
    {"prefix": "vor", "stem": "stellen", "meaning": "introduce", "hint": ""},
    {"prefix": "vor", "stem": "stellen", "meaning": "present", "hint": ""},
    {"prefix": "zu", "stem": "kommen", "meaning": "come up to", "hint": ""},
    {"prefix": "zu", "stem": "nehmen", "meaning": "increase", "hint": ""},
    {"prefix": "zu", "stem": "stellen", "meaning": "deliver", "hint": ""},
]