"""add hints to meaning

Revision ID: 428dca497a23
Revises: 8674e64359d8
Create Date: 2021-09-04 16:48:00.314895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428dca497a23'
down_revision = '8674e64359d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verb_meaning', sa.Column('hint', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verb_meaning', 'hint')
    # ### end Alembic commands ###
