"""add combinations

Revision ID: 8674e64359d8
Revises: 8c4877051a2a
Create Date: 2021-09-04 16:03:26.680995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8674e64359d8'
down_revision = '8c4877051a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verb_meaning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verb_prefix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verb_stem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix_id', sa.Integer(), nullable=True),
    sa.Column('stem_id', sa.Integer(), nullable=True),
    sa.Column('meaning_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meaning_id'], ['verb_meaning.id'], ),
    sa.ForeignKeyConstraint(['prefix_id'], ['verb_prefix.id'], ),
    sa.ForeignKeyConstraint(['stem_id'], ['verb_stem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combination')
    op.drop_table('verb_stem')
    op.drop_table('verb_prefix')
    op.drop_table('verb_meaning')
    # ### end Alembic commands ###
